import { MantineWrapper } from "@/libs/MantineWrapper";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lecture15",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineWrapper>{children}</MantineWrapper>
      </body>
    </html>
  );
}
